# Generated by Django 3.2.24 on 2024-02-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.SmallIntegerField(default=2011),
            preserve_default=False,
        ),
    ]
